name: Update NPM (Reusable)

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "18"

      version:
        required: true
        type: string

      gcp-project:
        required: true
        type: string

      wif-provider:
        required: true
        type: string

      service-account:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.wif-provider }}
          service_account: ${{ inputs.service-account }}
          project_id: ${{ inputs.gcp-project }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Bump version
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version

      - name: Run publish script
        run: |
          ./scripts/authenticate.sh
          npm install
          npm publish